-- Run this SQL in Supabase SQL Editor.
-- Then enable Authentication > Providers > Anonymous sign-ins.

create table if not exists public.poll_votes (
  id bigint generated by default as identity primary key,
  voter_id uuid not null,
  candidate_id integer not null check (candidate_id between 1 and 9),
  created_at timestamptz not null default now(),
  unique(voter_id)
);

alter table public.poll_votes enable row level security;

create or replace view public.poll_results as
select c.id as candidate_id, coalesce(count(p.id),0)::bigint as votes
from (values
 (1),(2),(3),(4),(5),(6),(7),(8),(9)
) as c(id)
left join public.poll_votes p on p.candidate_id=c.id
group by c.id
order by c.id;

create policy "anonymous can insert own vote"
on public.poll_votes for insert
to anon, authenticated
with check (auth.uid() = voter_id);

grant select on public.poll_results to anon, authenticated;
grant insert on public.poll_votes to anon, authenticated;

-- Important: do not grant SELECT on poll_votes.
